<?php

namespace App\Modules\Catalog\Infrastructure\Persistence;

use App\Models\Attribute;
use App\Models\AttributeValue;
use App\Modules\Catalog\Application\DTOs\AttributeData;
use App\Modules\Catalog\Application\DTOs\AttributeValueData;
use App\Modules\Catalog\Domain\Contracts\AttributeRepositoryInterface;
use Illuminate\Support\Collection;

class EloquentAttributeRepository implements AttributeRepositoryInterface
{
    public function findById(int $id): ?Attribute
        {
                return Attribute::query()
                            ->with('values')
                                        ->find($id);
                                            }

                                                public function findValueById(int $id): ?AttributeValue
                                                    {
                                                            return AttributeValue::query()
                                                                        ->with('attribute')
                                                                                    ->find($id);
                                                                                        }

                                                                                            public function findBySlug(string $slug): ?Attribute
                                                                                                {
                                                                                                        return Attribute::query()
                                                                                                                    ->where('slug', $slug)
                                                                                                                                ->first();
                                                                                                                                    }

                                                                                                                                        public function getAll(): Collection
                                                                                                                                            {
                                                                                                                                                    return Attribute::query()
                                                                                                                                                                ->with('values')
                                                                                                                                                                            ->orderBy('sort_order')
                                                                                                                                                                                        ->orderBy('name')
                                                                                                                                                                                                    ->get();
                                                                                                                                                                                                        }

                                                                                                                                                                                                            public function create(AttributeData $data): Attribute
                                                                                                                                                                                                                {
                                                                                                                                                                                                                        return Attribute::query()->create([
                                                                                                                                                                                                                                    'name' => $data->name,
                                                                                                                                                                                                                                                'slug' => $data->slug,
                                                                                                                                                                                                                                                            'type' => $data->type,
                                                                                                                                                                                                                                                                        'is_variant' => $data->isVariant,
                                                                                                                                                                                                                                                                                    'is_active' => $data->isActive,
                                                                                                                                                                                                                                                                                                'sort_order' => $data->sortOrder,
                                                                                                                                                                                                                                                                                                        ]);
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                public function update(
                                                                                                                                                                                                                                                                                                                        int $id,
                                                                                                                                                                                                                                                                                                                                AttributeData $data
                                                                                                                                                                                                                                                                                                                                    ): Attribute {
                                                                                                                                                                                                                                                                                                                                            $attribute = Attribute::query()->findOrFail($id);

                                                                                                                                                                                                                                                                                                                                                    $attribute->update([
                                                                                                                                                                                                                                                                                                                                                                'name' => $data->name,
                                                                                                                                                                                                                                                                                                                                                                            'slug' => $data->slug,
                                                                                                                                                                                                                                                                                                                                                                                        'type' => $data->type,
                                                                                                                                                                                                                                                                                                                                                                                                    'is_variant' => $data->isVariant,
                                                                                                                                                                                                                                                                                                                                                                                                                'is_active' => $data->isActive,
                                                                                                                                                                                                                                                                                                                                                                                                                            'sort_order' => $data->sortOrder,
                                                                                                                                                                                                                                                                                                                                                                                                                                    ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                            return $attribute->fresh('values');
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function delete(int $id): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Attribute::query()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->whereKey($id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->delete() > 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function createValue(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AttributeValueData $data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): AttributeValue {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return AttributeValue::query()->create([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'attribute_id' => $data->attributeId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'value' => $data->value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'slug' => $data->slug,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'display_value' => $data->displayValue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'color_hex' => $data->colorHex,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'sort_order' => $data->sortOrder,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public function updateValue(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int $id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AttributeValueData $data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ): AttributeValue {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $value = AttributeValue::query()->findOrFail($id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $value->update([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'attribute_id' => $data->attributeId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'value' => $data->value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'slug' => $data->slug,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'display_value' => $data->displayValue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'color_hex' => $data->colorHex,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'sort_order' => $data->sortOrder,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $value->fresh('attribute');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function deleteValue(int $id): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return AttributeValue::query()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->whereKey($id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ->delete() > 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }