<?php

namespace App\Modules\Settings\Application;

use App\Modules\Settings\Application\DTOs\SettingData;
use App\Modules\Settings\Application\UseCases\GetSetting;
use App\Modules\Settings\Application\UseCases\UpdateSetting;
use App\Modules\Settings\Domain\Contracts\SettingRepositoryInterface;

final class Settings
{
    public function __construct(
            private readonly GetSetting $getSetting,
                    private readonly UpdateSetting $updateSetting,
                            private readonly SettingRepositoryInterface $repository,
                                ) {
                                    }

                                        /**
                                             * Get a setting value.
                                                  */
                                                      public function get(
                                                              string $key,
                                                                      mixed $default = null,
                                                                          ): mixed {
                                                                                  return $this->getSetting->execute($key, $default);
                                                                                      }

                                                                                          /**
                                                                                               * Set or update a setting.
                                                                                                    */
                                                                                                        public function set(
                                                                                                                string $group,
                                                                                                                        string $key,
                                                                                                                                mixed $value,
                                                                                                                                        string $type = 'string',
                                                                                                                                                ?string $description = null,
                                                                                                                                                    ): void {
                                                                                                                                                            $this->updateSetting->execute(
                                                                                                                                                                        new SettingData(
                                                                                                                                                                                        group: $group,
                                                                                                                                                                                                        key: $key,
                                                                                                                                                                                                                        value: $value,
                                                                                                                                                                                                                                        type: $type,
                                                                                                                                                                                                                                                        description: $description,
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                         * Get a boolean setting.
                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                  public function boolean(
                                                                                                                                                                                                                                                                                                          string $key,
                                                                                                                                                                                                                                                                                                                  bool $default = false,
                                                                                                                                                                                                                                                                                                                      ): bool {
                                                                                                                                                                                                                                                                                                                              return (bool) $this->get($key, $default);
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                                           * Get an integer setting.
                                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                                    public function integer(
                                                                                                                                                                                                                                                                                                                                                            string $key,
                                                                                                                                                                                                                                                                                                                                                                    int $default = 0,
                                                                                                                                                                                                                                                                                                                                                                        ): int {
                                                                                                                                                                                                                                                                                                                                                                                return (int) $this->get($key, $default);
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                             * Get a float setting.
                                                                                                                                                                                                                                                                                                                                                                                                  */
                                                                                                                                                                                                                                                                                                                                                                                                      public function float(
                                                                                                                                                                                                                                                                                                                                                                                                              string $key,
                                                                                                                                                                                                                                                                                                                                                                                                                      float $default = 0.0,
                                                                                                                                                                                                                                                                                                                                                                                                                          ): float {
                                                                                                                                                                                                                                                                                                                                                                                                                                  return (float) $this->get($key, $default);
                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                                                                                                                                               * Get a string setting.
                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function string(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                string $key,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        string $default = '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (string) $this->get($key, $default);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * Get a JSON/array setting.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public function json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  string $key,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          array $default = [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ): array {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $value = $this->get($key, $default);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return is_array($value) ? $value : $default;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * Get all settings grouped by group name.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function getSettingGroups(): array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->repository
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->getAll()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->groupBy('group')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ->map(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fn ($settings) => $settings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->mapWithKeys(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fn ($setting) => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $setting->key => $setting->getTypedValue(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->toArray()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ->toArray();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * Get all settings belonging to a group.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public function getGroup(string $group): array
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return $this->repository
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ->getByGroup($group)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ->mapWithKeys(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fn ($setting) => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $setting->key => $setting->getTypedValue(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ->toArray();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * Check if a setting exists.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function has(string $key): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $this->repository->findByKey($key) !== null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Delete a setting.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  public function delete(string $key): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return $this->repository->delete($key);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }