<?php

namespace App\Modules\Catalog\Presentation\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreAttributeRequest extends FormRequest
{
    public function authorize(): bool
        {
                return true;
                    }

                        public function rules(): array
                            {
                                    return [
                                                'name' => [
                                                                'required',
                                                                                'string',
                                                                                                'max:255',
                                                                                                            ],

                                                                                                                        'slug' => [
                                                                                                                                        'required',
                                                                                                                                                        'string',
                                                                                                                                                                        'max:255',
                                                                                                                                                                                        'alpha_dash',
                                                                                                                                                                                                        Rule::unique('attributes', 'slug'),
                                                                                                                                                                                                                    ],

                                                                                                                                                                                                                                'type' => [
                                                                                                                                                                                                                                                'required',
                                                                                                                                                                                                                                                                'string',
                                                                                                                                                                                                                                                                                Rule::in([
                                                                                                                                                                                                                                                                                                    'select',
                                                                                                                                                                                                                                                                                                                        'text',
                                                                                                                                                                                                                                                                                                                                            'color',
                                                                                                                                                                                                                                                                                                                                                                'number',
                                                                                                                                                                                                                                                                                                                                                                                    'boolean',
                                                                                                                                                                                                                                                                                                                                                                                                    ]),
                                                                                                                                                                                                                                                                                                                                                                                                                ],

                                                                                                                                                                                                                                                                                                                                                                                                                            'is_variant' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                            'sometimes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'boolean',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'is_active' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'sometimes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'boolean',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'sort_order' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'sometimes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'integer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'min:0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }