<?php

namespace App\Modules\Catalog\Presentation\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreCategoryRequest extends FormRequest
{
    public function authorize(): bool
        {
                return true;
                    }

                        public function rules(): array
                            {
                                    return [
                                                'name' => [
                                                                'required',
                                                                                'string',
                                                                                                'max:255',
                                                                                                            ],

                                                                                                                        'slug' => [
                                                                                                                                        'required',
                                                                                                                                                        'string',
                                                                                                                                                                        'max:255',
                                                                                                                                                                                        'alpha_dash',
                                                                                                                                                                                                        Rule::unique('categories', 'slug'),
                                                                                                                                                                                                                    ],

                                                                                                                                                                                                                                'parent_id' => [
                                                                                                                                                                                                                                                'nullable',
                                                                                                                                                                                                                                                                'integer',
                                                                                                                                                                                                                                                                                'exists:categories,id',
                                                                                                                                                                                                                                                                                            ],

                                                                                                                                                                                                                                                                                                        'description' => [
                                                                                                                                                                                                                                                                                                                        'nullable',
                                                                                                                                                                                                                                                                                                                                        'string',
                                                                                                                                                                                                                                                                                                                                                    ],

                                                                                                                                                                                                                                                                                                                                                                'image_path' => [
                                                                                                                                                                                                                                                                                                                                                                                'nullable',
                                                                                                                                                                                                                                                                                                                                                                                                'string',
                                                                                                                                                                                                                                                                                                                                                                                                                'max:2048',
                                                                                                                                                                                                                                                                                                                                                                                                                            ],

                                                                                                                                                                                                                                                                                                                                                                                                                                        'is_active' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                        'sometimes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'boolean',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'sort_order' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'sometimes',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'integer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'min:0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }