<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ProductVariant extends Model
{
    use HasFactory;

        protected $fillable = [
                'product_id',
                        'name',
                                'price',
                                        'compare_at_price',
                                                'cost_price',
                                                        'sku',
                                                                'barcode',
                                                                        'weight',
                                                                                'length',
                                                                                        'width',
                                                                                                'height',
                                                                                                        'is_active',
                                                                                                                'sort_order',
                                                                                                                    ];

                                                                                                                        protected function casts(): array
                                                                                                                            {
                                                                                                                                    return [
                                                                                                                                                'price' => 'decimal:2',
                                                                                                                                                            'compare_at_price' => 'decimal:2',
                                                                                                                                                                        'cost_price' => 'decimal:2',

                                                                                                                                                                                    'weight' => 'decimal:3',
                                                                                                                                                                                                'length' => 'decimal:3',
                                                                                                                                                                                                            'width' => 'decimal:3',
                                                                                                                                                                                                                        'height' => 'decimal:3',

                                                                                                                                                                                                                                    'is_active' => 'boolean',
                                                                                                                                                                                                                                                'sort_order' => 'integer',
                                                                                                                                                                                                                                                        ];
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                public function product(): BelongsTo
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                            return $this->belongsTo(
                                                                                                                                                                                                                                                                                        Product::class,
                                                                                                                                                                                                                                                                                                    'product_id'
                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    public function attributeValues(): BelongsToMany
                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                return $this->belongsToMany(
                                                                                                                                                                                                                                                                                                                                            AttributeValue::class,
                                                                                                                                                                                                                                                                                                                                                        'product_variant_attribute_value',
                                                                                                                                                                                                                                                                                                                                                                    'product_variant_id',
                                                                                                                                                                                                                                                                                                                                                                                'attribute_value_id'
                                                                                                                                                                                                                                                                                                                                                                                        )->with('attribute');
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                public function images(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                            return $this->hasMany(
                                                                                                                                                                                                                                                                                                                                                                                                                        ProductImage::class,
                                                                                                                                                                                                                                                                                                                                                                                                                                    'product_variant_id'
                                                                                                                                                                                                                                                                                                                                                                                                                                            )->orderBy('sort_order');
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function primaryImage(): ?ProductImage
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->images()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->where('is_primary', true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->first();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function isActive(): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $this->is_active;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function effectivePrice(): mixed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->price ?? $this->product?->price;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function effectiveWeight(): mixed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return $this->weight ?? $this->product?->weight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }