<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

        protected $fillable = [
                'name',
                        'slug',
                                'short_description',
                                        'description',
                                                'brand_id',
                                                        'product_type',
                                                                'status',
                                                                        'price',
                                                                                'compare_at_price',
                                                                                        'cost_price',
                                                                                                'sku',
                                                                                                        'barcode',
                                                                                                                'weight',
                                                                                                                        'length',
                                                                                                                                'width',
                                                                                                                                        'height',
                                                                                                                                                'weight_unit',
                                                                                                                                                        'dimension_unit',
                                                                                                                                                                'is_active',
                                                                                                                                                                        'is_featured',
                                                                                                                                                                                'sort_order',
                                                                                                                                                                                    ];

                                                                                                                                                                                        protected function casts(): array
                                                                                                                                                                                            {
                                                                                                                                                                                                    return [
                                                                                                                                                                                                                'price' => 'decimal:2',
                                                                                                                                                                                                                            'compare_at_price' => 'decimal:2',
                                                                                                                                                                                                                                        'cost_price' => 'decimal:2',

                                                                                                                                                                                                                                                    'weight' => 'decimal:3',
                                                                                                                                                                                                                                                                'length' => 'decimal:3',
                                                                                                                                                                                                                                                                            'width' => 'decimal:3',
                                                                                                                                                                                                                                                                                        'height' => 'decimal:3',

                                                                                                                                                                                                                                                                                                    'is_active' => 'boolean',
                                                                                                                                                                                                                                                                                                                'is_featured' => 'boolean',

                                                                                                                                                                                                                                                                                                                            'sort_order' => 'integer',
                                                                                                                                                                                                                                                                                                                                    ];
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            public function brand(): BelongsTo
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                        return $this->belongsTo(
                                                                                                                                                                                                                                                                                                                                                                    Brand::class,
                                                                                                                                                                                                                                                                                                                                                                                'brand_id'
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                public function categories(): BelongsToMany
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                            return $this->belongsToMany(
                                                                                                                                                                                                                                                                                                                                                                                                                        Category::class,
                                                                                                                                                                                                                                                                                                                                                                                                                                    'category_product',
                                                                                                                                                                                                                                                                                                                                                                                                                                                'product_id',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'category_id'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )->withPivot([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'is_primary',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'sort_order',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public function variants(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $this->hasMany(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ProductVariant::class,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'product_id'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )->orderBy('sort_order');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function images(): HasMany
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $this->hasMany(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ProductImage::class,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'product_id'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )->orderBy('sort_order');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function isSimple(): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->product_type === 'simple';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function isVariable(): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return $this->product_type === 'variable';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public function isActive(): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $this->is_active;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public function isPublished(): bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return $this->status === 'published' && $this->is_active;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function primaryCategory(): BelongsToMany
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->categories()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->wherePivot('is_primary', true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function primaryImage(): ?ProductImage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $this->images()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ->where('is_primary', true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ->first();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }